ohmec/ohmec

COMMITTERS, README.md, ohmec.css, ohmec.html, ohmec.js, ohmec_data_na.js, runlint, time_slider.js
=> add copyright banner to files, committer list

geo_features.js, index.html, ohmec.js, runlint
isolate the style information into its own .js file for easier maintenance going forward
addresses #8
=> isolate the style information into its own .js file

index.html, utilities/geojson2kml.py, utilities/kml2geojson.py
KML has much less data than geoJSON, so this is only an assist utility for now. A lot of GEOJSON content needs to be added and the snippet needs to be merged within the larger database. For now this should suffice, so fixes #16.
=> Add utility to assist converting KML to geoJSON

index.html
=> clean up of website pointers

ohmec.js
This fixes two bugs, first by clamping the zoom from 2..15 (rather the default 0..18) (fixes #105) and the precision issue for large zooms (fixes #104) by using `toFixed` instead of `toPrecision` in the javascript.
=> Fix zoom issues

index.html, ohmec.css
`index.html` got cluttered in one of the last two check-ins, fixing.
=> Fix unsightly index.html clutter

ohmec.js, time_slider.js
Fixes #136 
This fixes all of the cross-referenced globals between `ohmec.js` and `time_slider.js`. There are still some between `ohmec.js` and `geo_features.js`, but since the latter might roll into the databases with #133 I will leave them as is now.
Hopefully I didn't break any functionality, need some regression tests...
=> Clear up cross-references globals

index.html
Signed-off-by: Warren Packard <warrenjp@gmail.com>
Fixes #135
=> Updated OHMEC summary text

ohmec.js
Fixes #169 
This fixes the bug discovered in the #165 patch.
=> Fix enddatestr on dec/31

ohmec.js
Fixes #173 
Rewords the sentence from:
```
OHMEC will work with Native Land Digital to attempt to get more accurate representation of where each tribe was and when.
```
to
```
OHMEC will work with Native Land Digital to attempt to represent movements of the Native American tribes throughout their history.
```
=> Reword popup for NL

index.html
=> Fix missing NL

ohmec.js, ohmec_data_ancient_americas.js, ohmec_data_eur.js, ohmec_data_na.js
This allows the content to be more similar with `popup` and `style`
=> Move viewpoint information into its own structure within database

ohmec.js, ohmec_data_ancient_americas.js, ohmec_data_eur.js, ohmec_data_na.js, ohmec_data_nl.js
Fixes #205 
This adds the ability for the database to have multiple popup windows based upon time and geography. Multiple popups can be rendered at one time if they match in time and place.
=> Add ability for multiple popups

ohmec.js
Addresses #222 
This adds the URL ability to turn off the popups in case they are annoying to users. Unfortunately I haven't found an elegant way to add an on-map checkbox that will disable it. I had one method but I couldn't debug why it would fail on corner cases, and have dropped it for now. Will leave the issue still open and return to it later.
=> Add ability to turn off popups from URL and page

ohmec.js
Fixes #225 
This PR adds animation for `fontcolor`, but also handles the case when one feature designates a `fontcolor` with an alpha setting, and the other does not. In those cases it animates from the given alpha to `0xff` for the feature that doesn't have an alpha setting.
This also fixes a bug that I didn't notice before where an animated value gets "stuck" at the destination value, and then no longer animates. I noticed this for `fontcolor` but the same problem seems to have existed for `fillColor` etc.
=> Add animation for fontcolor

utilities/geojson2kml.py
fixes #241 
This adds pre-American US- and non-US-claims in Alaska and Hawaii region
=> Add pre-American Alaska and Hawaii occupations

time_slider.js
Fixes #276 
Clears any pinned infobox material whenever the timeline slider is moved
=> Fix infobox pin bug during timeline mod

ohmec.css, ohmec.js
I experimented with the idea of having the infobox match the color of the highlighted feature, and think I prefer it. Will check in and "sit with it" for a while to see if it needs tinkering.
=> Change the infobox background color to match the underlying feature

index_aciv.html
Removes reference to one source book, at least for now, as the scope is slightly larger
=> Clean up messaging on index_aciv.html

index_meso.html, ohmec_data_meso.js
Add mini-study link on the Mesoamerican page for the Cortes march. Also fix typo in Period data for Tenochtitlan and Aztec Empire.
=> add mini-study for Cortes march
