ohmec/ohmec

geo_features.js
ohmec.css
ohmec.js
ohmec_data_na.js
time_slider.js

Fixes #30 
This adds information on the entity types and names, start and end date, and has a clickable link for source if it exists. In order to get the hover information to "stick" in order to click the link, the user can click on a feature to hold it for a few seconds.

Add information box

---

utilities/geojson2kml.py
utilities/kml_edge_copy.py
utilities/merge_geometry.py

Fixes #32 
This utility works with KML since that is the current format of choice for editing. It takes two KML files, and with no other arguments, lists the coordinates that are in common. To do the editing, it requires a start and endpoint, and which direction on both polygons to do the copy (N, S, E, W). It errors out if it was unsuccessful.
The script is pretty clunky right now and could be cleaned up later.

Add new utility to copy edges of a polygon.

---

index.html
ohmec.css
ohmec.js

Fixes #41 
Adds URL arguments ?lat= ?lon= and ?z= to override default latitude, longitude and/or zoom

Add ability to change default lat/lon/z

---

index.html
ohmec.css
ohmec.js

Multiple webpage improvements, including
* at the bottom of index.html, provides a direct-link URL that allows direct re-creation of the current viewpoint (current date, lat/lon, zoom value) (fixes #63); this is updated on every timeline change, and every zoom or pan
* increases the size of the map to 95% width and 60% height, which scales as the document window scales
* makes zoom granularity 0.5 instead of 1.0

Create direct URL link for easy reference

---

ohmec.js

Fixes #65 
For some reason you can't have a different value for zoomDelta than zoomSnap. When different either one or both of the +/- buttons will fail. Leaving with zoom delta of 0.5 for now.

Fix #65 bug in zoom out button

---

README.md
index.html

Fixes #6 
Newly created explanatory collateral is linked into the project README and into the main index.html page.

Adding pointers to newly created explanatory collateral.

---

time_slider.js

Fixes #118 
PR #106 changed the variables within `ohmec.js` to make them more consistent. Unfortunately they reach into `timeline_slider.js` and the linting tools don't do any^H^H^H a good job of checking variables across files. This does a quick patch to avoid poor representation, but another issue will be filed to get better linting in place.

Fix introduced bug with timeline slider

---

ohmec.js

Fixes #116 
The world in Leaflet is limitless in that you can pan indefinitely east and west. We've limited the zoom in #106 to make sure it doesn't look silly with duplications, but due to a limitation in Leaflet, only one copy of the overlays is provided on the duplicates anyway. So panning east or west shows an "empty world".
This uses a feature of Leaflet to disallow panning beyond the "populated world". It also cuts out Antarctica and the unpopulated part of the Arctic circle since those aren't going to be covered and don't render beautifully on this Mercator projection anyway.

Fix pan to avoid going into deadzones

---

index.html
ohmec.js
time_slider.js

Addresses #94 
This is still exploratory, but implements a selectable "smart step" button feature, whereby the current viewpoint bounds rectangle is compared against those features that would be added or removed by the step forward or backward. If the bounds intersect for any of the added or removed features, then the step is used, else it tries the next step. It isn't perfect since bounds can intersect while the actual features might not intersect, but otherwise it works pretty well.
If this were to be merged, it would come with a web-variable override option, but in this draft "smart step" is always true.

Implementing "smart step" buttons

---

index.html
ohmec.css
ohmec.js

Fixes #125 
This gives us 6 base layer options, and changes the default to the most innocuous.
It also key maps `0` to `5` to toggle maps, or you can use the layer selector in the upper right corner.

Add ability to change base layer map

---

index.html
ohmec.css
ohmec.js
time_slider.js

More clean up to `index.html` page, including making option tables more readable; showing defaults for `&override` values; adding missing `&background=` override; preparing for BC dates by allowing BC input, and using BC suffix instead of negative years on dates.

Clean up HTML front page, prepare for BC

---

index.html
ohmec.js
time_slider.js

Fixes #127 
Fixes #134 
This adds the `zoom to Feature` request of #127 with keypress value of `z`, as well as giving keyboard shortcuts for the buttons `Step +` (`>` or `.`), `Step -` (`<` or `,`), and advance (`a`) toggle. In addition, to fix feature request #134, this adds `r` to reset to initial lat/lon/z settings.

Add more keyboard shortcuts

---

index.html
ohmec.css
ohmec.js
time_slider.js

fixes #91 
This small fix pushes a selected layer "to the back", thereby allowing user's to toggle between overlapping layers. In my brief tests, double-stacked layers were selected alternately with each "info click", which should suffice. I will add this to the documentation.

Allow toggling of layer selection

---

index.html
ohmec.js

If we want to show the potential of the animation, it requires online hacks that are clumsy and time consuming. I would still prefer this stuff be far from "productized", since the data gathering was very quick and dirty. So making this an "easter egg". It requires that the `ohmec_data_eur.js` file be loaded always, but it is relatively small at this time so doesn't overload the system. adding `?easter` or `?easteregg` to the URL will snap it to the iceage Europe viewpoint. Keeping this unadvertised at this point, for demonstration only.

Adding "easter egg" to show animation potential

---

index.html
ohmec.js
ohmec_data_na.js

This completes the job started in #154 and abandoned since the database had moved quite a bit.
This gives a command-line option (using `?nl`) to visualize the data from `native_lands.ca`. For now I would like to leave it unadvertised until a) we have a discussion with them about how they would like to see; b) we document it better; c) we add a pop-up when selected that gives the correct credit. For now this is for our internal viewing to discuss and agree upon the style.
@warrenjp LMKWYT

Adding `?nl` feature to enable native_lands.ca information

---

ohmec.js

Fixes #164 
This fixes the end-date/start-date gap rendering bug by setting the end time of an end date to be `23:59:59` or `11:59:59pm`.

Fix minor bug with end dates

---

ohmec.js

Addresses #166 
This allows Points of Interest to be in the `entity2` property. It does not yet color them with the `entity1`s style information, which is the second half of #166 so leaving it open still for that feature upgrade.

Allow Points of Interest to be entity2

---

ohmec.js
ohmec_data_eur.js

Fixes #182 
This adds animation ability to morph colors and opacities. This can be useful when moving from one ancient "culture" to another without looking like a step function from, say, Magdalenian Culture to Ahrensburg Culture. I've included one example in the European play area (`?easter`) but doesn't really take advantage of the conversion just yet, only used for debugging purposes.
Unrelated: clipping BC dates to ignore day and month, only using year.

Animate stroke and fill colors and opacities

---

ohmec.js
ohmec_data_eur.js
ohmec_data_na.js

Fixes #184 
This adds `layerDepth` as a style element, rather than a property as suggested in #184. This allows the style property to be inherited for all types. It is envisioned as being used by `geography` types such as land bridges that appeared in Pleistocene times.

Add layerDepth property

---

ohmec.js
ohmec_data_eur.js

fixes #186 
fixes #187
This adds two new properties: `iconScale` and `noLabel`. This allows POI point icons to be scale (their labels with them), and for the database to declare that an entity shouldn't have a label.

add iconScale and noLabel properties

---

ohmec.js
ohmec_data_eur.js
ohmec_data_na.js
time_slider.js

Fixes #189 
Fixes #190 
This patch allows the user to override the default parameters for the Advance button, which are 240 intervals of 250ms, for a total advance of 2 minutes. New parameters `?advInt=n` and `?advDur=m` change the number of intervals to `n`, and the duration of the intervals to `m` milliseconds, respectively.
In addition, this patch allows the database to override the default start, current, and end times for the timeline slider. They are still overrideable by the URL modifiers. The `_data_na` and `_data_eur` databases set their appropriate values.

Override start/end date in db, advance parameters in URL

---

ohmec.js
ohmec_data_eur.js
ohmec_data_na.js

Fixes #189 
This adds the new functionality added by the reopened #189, ability to set default lat/lon/z from the database so that it doesn't have to be baked into the `ohmec.js` script.

Add ability to set default lat/lon/z from database

---

index.html
ohmec.css
ohmec.js
ohmec_data_ancient_americas.js
ohmec_data_eur.js
ohmec_data_nl.js

Fixes #197 
This adds the ability to put popup information into a database, rather than in the primary Javascript file(s). It moves the Native Lands popup into that database, and adds a popup for the European and Ancient Americas data sets too. In addition, this adds some information to the `index.html` webpage to describe the different studies.

Add ability to make popups for any dataset

---

ohmec.js

Fixes #209 
This closes popups when their time span is exited. There still seems to be a strange leaflet bug that renders two popups for one entry sometimes. When this happens, only one of those two is auto closed, but until I can catch the bug in the act I'm not sure how to fix.

auto-close popups when their time span is exited

---

ohmec.js

fixes #232 
This PR adds the ability to animate LineStrings in a manner very similar to animating polygons. The documentation has been updated, but the short version is the following:
1. features of geometry type `LineString` give a 2D string of coordinates for id `fromID`
2. adding the `animateTo` attribute with id `toID` animates from the start date of `fromID` to the enddate of `fromID`, adding any additional points from `toID` to the line as the time progresses.
3. no error checking is done except to ensure that `toID` has equal or more number of line vertices as `fromID`
4. the coordinates of the endpoint(s) of the added line segments are interpolated based upon the point in time being displayed. For example, if `toID` adds one vertex, and `fromID` animates from January 1 to December …

add ability to animate LineString

---

ohmec.js
utilities/check_boundaries.py
utilities/merge_geometry.py

fixes #236 
This adds a feature `coordinate_copy` to the database. Replacing `coordinates`, this entry requests to copy the existing coordinates from another feature, given as the argument. This can speed up development and shrink the native database. It is unclear at this time how important that is to performance, but it still can reduce cut/paste or copy errors. The `ohmec_data_na.js` database was scrubbed and reduced 17% in area by implementing 170 coordinate copies out of a total of 1330 (12%).
The documentation has been updated to define the feature, and utilities have been modified to use copies.

add ability to create coordinate_copy

---

ohmec.js
poi_camp.svg
utilities/geojson2kml.py

Fixes #238 
This adds the Lewis and Clark expedition from 1804-1805 from St Louis to the mouth of the Columbia River Oregon. It animates it as an increasing linestring that "lasts" until 1825 on the map. Unlike the Columbus voyages and the Cortes journey into Tenochtitlan, it breaks the linestrings into segments so that they don't get massively large. Visually there is no noticeable difference except that if one mouseovers the linestring only the particular segment is highlighted.
Along the way, a new POI was created: camp. This is used to designate the 6 camps where the voyagers stayed for a period of time.

Add Lewis and Clark expedition as animated LineString

---

ohmec.js
utilities/check_boundaries.py
utilities/geojson2kml.py
utilities/merge_geometry.py

Fixes #243
Adds ability to copy coordinates from multiple features into one new feature. Note this is not identical to a feature merge, which might combine two adjacent polygons into one, but rather an array of polygons into one `MultiPolygon`. For instance if one were to do a `coordinate_copies` array of `["TX","LA"]`, the border between Texas and Louisiana would still be visible.
A better example, and the inspiration for this feature, is the myriad combinations of islands in the Caribbean as they shift from one entity (eg. British Leeward Islands) to another (eg. West Indies Federation)

Add ability to do coordinate_copies from array of sources

---

ohmec.js

Fixes #245 
This adds the ability to do line spacing (aka "kerning") to spread (or crowd) letters in a label, useful for creating labels that span a wide length eg. Caribbean islands.
The feature is to add `labelSpacing` with a float value roughly from 0.0 (no effect) upwards. A value of 1.0 has twice the space as 0.0 (default), making the label width say 25-40% wider (depending upon the font). This is executed by simply passing the value on directly to the created SVG layer using SVG's `letter-spacing=` option.
The documentation has been updated.

Add line spacing feature

---

index.html
index_aa.html
index_cherokee.html
index_meso.html
index_nl.html
index_viking.html
ohmec.js
tablinks.js

Fixes #220 
This pulls the Mesoamerican theater features into their own database, `ohmec_data_meso.js`, and removes most of it from `ohmec_data_na.js`. While they are all North American, the goal was to reduce the size of the latter, and highlight the time span of the former. Unfortunately there is a 100 year overlap, so there are several dozen features that are in both. Nominally "meso" is from 1800 BC to 1600, and "NA" is 1492 to present day. And "meso" focuses on latitudes of 30˚N and lower. An extra `.html` frontpage is given to Meso and links to it are presented on each of the other `.html` pages. In addition I'm experimenting with two "sub-focus" links on the meso page, one for the 100 years of Aztec history; the other on Columbus' voyages.

Slice the Mesoamerican theater off from the rest of North America

---

runlint

I noticed a few labeling errors in the database (`labalScale` instead of `labelScale`, `editdate` instead of `editdatestr`) and cleaned those up. While doing so I got a little OCD and put all of the properties in a fixed order for the features. Makes no material or performance difference. Also, added the other databases to the linting script

Slightly over-OCD cleanup of the database

---

ohmec.css
ohmec.js

Fixes #222 
This adds a radio button on the panel that allows popups to be enabled or disabled. The popup is minimized unless hovered over, in which case it explains its purpose. Thereby it is of minimal intrusion. Disabling the popups can still be done via URL modification, and the URL modification text line is updated by clicking the radio button

Add ability to enable/disable popups

---

utilities/kml2geojson.py

Fixes #261 
Cc @kt1122
This change to `utilities/kml2geojson.py` makes the parsing of the KML sublayers more lenient, and inserts today's date for `startdatestr` (it was misspelled this whole time 😲 anyway). The new pattern matching algorithm for the sublayer (ie. shape within the layer) is as follows:
1. [`NAME1`] `NAME2` Polygon `n`
a. creates a MultiPolygon with ID `NAME1` if it doesn't already exist
b. appends the shape's coordinates to the MultiPolygon
c. gives it the `entity2name` of `NAME2` (all these can of course be edited later)
2. `NAME` Polygon `n` (<<-- this feature is the newly added one)
a. creates a MultiPolygon with ID `NAME` if it doesn't already exist
b. appends the shape's coordinates to the MultiPolygon
c. leaves `entity2name` unknown (`"XXXX"`)
3. `NAME`
a. creates a …

Augment utility kml2geojson

---

ohmec.js

Fixes #264
Noticed one case where one of the animating tribes (proto Maya in this case) had messed up font information when in highlight mode. The fix is to make sure that animating type features do not use the highlight font color, else it messes up the animation.

Fix one case of animating borderless highlighting

---

utilities/make_point.py

Fixes #266
This utility can read in multiple coordinate formats and create an editable Point coordinate type in geojson. From the Usage banner, here are some examples of types that are convertible. These are ones found in wikipedia pages and other locations:
37°15′11″N 115°29′05″W
28°41′25.21521″S 144°42′09.1521″E
15° 44′ 29″ N 99° 55′ 44″ W
45°22′46.12126″S, 85°49′14.8621″E
49°07′S 158°40′E
79°8.2512′N 44°42.1512512′W
6.12371°S 15.9281281°E
56.9521°N 171.14129°W
-26.6129, 100.582571
26.9121,-99.124867
S72° 41.1219 E101° 51.21912
S72° 51.6189 W99° 4.51216
The usage is one of two ways. You can put the input strings into a single file, then read that in:
```
terminal> ./utilities/make_point.py filename
```
Or you can run it "live" and input the strings one by one:
```
terminal> …
```

Add utility to create Point type given coords

---

ohmec_data_meso.js

Minor fix: I noticed that a raft of 16th century Spanish settlements in the Mexico/Central America region had end dates of `present`, which might be accurate, but as it concerns the notion of a Spanish settlement, I have changed the end date to 1810 when Mexico began its fight for independence. This goes under the category of their "end date of importance" (the general theme of end dates for Point locations) being the end of Spanish ownership of them.

Fix of end date for colonial spanish settlements

---

about.html
index.html
index_aa.html
index_cherokee.html
index_ma.html
index_meso.html
index_nl.html
index_viking.html
ohmec.css
ohmec.js

Fixes #270
This check-in adds three text-input forms to each of the html pages. (Sidenote: it would be preferred to share this snippet and not have to cut/paste into each `.html` file; this is akin to `tablinks.js`, but that is not a very elegant solution either. Will leave as is for now.) These three forms allow the user to more obviously modify the default start date, current date, and/or end date rather than having to change the URL modifiers.
As currently coded, the modification of any of these forms immediately re-loads the current page with the modification implemented. This is as opposed to say attempting to live-update the timeline while keeping the current page still loaded. Since there is no history stored within a map interaction, this seems sufficient. Also, modification of …

Allow user to more easily modify initial dates

---

time_slider.js

Fixes #279 
I found these two bugs while playing with PR #268. The smartstep toggle wasn't getting fixed in the timeline slider itself, only in the display of the button. And there are some cases (also seen in Ancient Americas) where - if the features end before `present` - you can't step backwards since the last entry of "Dates of Interest" is undefined. In that case, always move backwards, regardless of smart step.

Fix bug with smart step in timeline slider

---

ohmec.css
ohmec.js
ohmec_data_meso.js

Fixes #269 
This adds the ability to add the notion of a period (was thought of as "entity_phase" in #269) for a feature. This is done similarly to style matching, with the addition of a time period.
This example was added to the meso american study:
```
"periods":[
{ "match":{ "entity1type": "civilization", "entity1name": "Maya"},
"periods":[
{ "startdatestr":"2000BC", "enddatestr":"1001BC", "period":"Early Preclassic Period" },
{ "startdatestr":"1000BC", "enddatestr":"351BC",  "period":"Middle Preclassic Period" },
{ "startdatestr":"350BC",  "enddatestr":"249",    "period":"Late Preclassic Period" },
{ "startdatestr":"250",    "enddatestr":"549",    "period":"Early Classic Period" },
{ "startdatestr":"550",    "enddatestr":"829",    "period":"Late Classic Period" },
{ …
```

Add ability to add time periods to database

---

ohmec.css
ohmec.js
ohmec_data_meso.js
time_slider.js

Fixes #296
This adds the ability to change (slightly) the style of markup in popups, including the background color, font name, font size, font color, and link font color. The documentation will be updated for this feature before it is committed.
Two popups have been added to "link" the Mesoamerican study with the (default) Modern North America study, exhibiting some of the popup style features (to use a red background).

Add ability to change popup styling, and create bridge popups

---

about.html
ohmec.js

Fixes #301 
This checks the keypress for a number 1-9, and if a feature is selected, and that feature has that number of sources or more, opens the feature source indicated by the press. Falls back on changing the background layer otherwise.
In addition, this adds a keyboard character a la 1️⃣ to guide the user to the notion of the keypress.
This updates the `about.html` page to indicate the interaction change, but still wish there was an easier way to convey this upon first viewing.

Allow keypress of 1-9 to open up sources

---

ohmec.js
ohmec_data_meso.js

Fixes #308 
This adds the emperors ("huetlatoni") of the Aztec Alliance and Tenochtitlan (Mexica) tribes. For now it doesn't add the other members (Tlacopan, Texcoco) of the alliance, and marks the *huetlatoni* of the Aztec Alliance as that of Tenochtitlan.
In the process, found some nit bugs in the `periods` syntax checking and a few unused variables, that are cleaned up.

Add leadership (huetlatoni) of Aztec/Mexica/Tenochtitlan

---

ohmec_data_meso.js

A viewer commented:
Please don't use the phrase "tribal civilizations." There is an academic literature in which that's a major oxymoron, but even beyond that literature it's sort of demeaning to qualify the word "civilization" for one group if you wouldn't also do it for the Greeks and Chinese. Just say "civilizations."
This has been fixed in the popup for the Olmec

Fix poor terminology choices
